### ISSUE TITLE
Compatibility with Draw.io Plugin

### ISSUE THREAD

**Issue by estebanramos** [IceWreck/Argon-Dokuwiki-Template#51]
Hello, the Argon Template is not working with Drawio plugin. It just opens a new blank page. Any help on this?

**Comment by jacksitlab** [comment]
I have set the z-index in the drawio plugin config to 1300. Then it is shown on my side.

**Comment by estebanramos** [comment]
I can see previous added diagrams but cannot edit them (I clicked them and it redirects me to a blan page), neither I see the plugin icon. Do you have a solution for that?

**Comment by jacksitlab** [comment]
Sadly I cannot reproduce this since I have to many changes done on the template stylesheet. But you can easily find out if you check in the browser console first that there are no javascript errors and if this is the case then just check the z-index of the sidebar and the header.

**Comment by estebanramos** [comment]
Ok, what parameters exactly did you change in order to work?

**Comment by jacksitlab** [comment]
The answer is: A lot:
https://github.com/jacksitlab/Argon-Dokuwiki-Template/commit/1d094796577cb4dac0b02afeac2e5a72bb7ba5df

With these changes I have no JS errors anymore. DrawIO is working. The same for ckgedit, plantuml parser and indexmenu plugin.
But I also changed a lot of css information because I wanted a more confluence-like look which when I'll have have some more time I'll try to finish. Most important is the WYSIWYG Editor to get much better in fact the confluence one is a really good one.

**Comment by estebanramos** [comment]
Thanks for sharing your Fork! Did you change something besides the template? I've downloaded the fork and still fails to render the Draw.io Icon when editing and page, and also if I click on a rendered Drawio diagram it redirects me to an empty page.

Edit: My mistake, I didn't change the git branch to the patch's branch, now it works! Thank you,

**Comment by jacksitlab** [comment]
I have tested it now with a clean installation of dokuwiki-2020-07-29 with my argon template and drawio plugin set up with config:

- zIndex=1300
- url=http://localhost:9001

and it is working. I mean I can see all controls and can save it. 
Short hint. I am using a local instance of a drawio server. Here my local docker-compose.yml
```
version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - 9000:80
    volumes:
      - ./public_html:/var/www/html
    restart: always
    networks:
      - dokuwiki-network
  drawio:
    image: jgraph/drawio
    ports:
      - 9001:8080
    networks:
      - dokuwiki-network
  
  plantuml:
    image: plantuml/plantuml-server:jetty
    networks:
      - dokuwiki-network

networks:
  dokuwiki-network:
    external:
      name: dokuwiki-network

```
